# -*- coding: utf-8 -*-
"""Case_Integral_Trust.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YpDq3V3stKTvJhrzXcFsplATNXW6Pfy2

Teste Prático : Nível : Estagio de Dados
=========================================================
Contexto do Problema: Você foi convidado a analisar um conjunto de dados de vendas de uma empresa de e-commerce. O objetivo principal é identificar padrões e gerar insights iniciais que ajudem a equipe de negócios a compreender melhor as vendas e as preferências dos clientes.

**Parte 1: Análise Estatística e Exploratória Básica (40% da pontuação)**

1.	**Descrição**: Usando o conjunto de dados fornecido (dataset de vendas), realize uma análise exploratória inicial, com foco nos seguintes pontos:
  -	Cálculo de estatísticas básicas, como média, mediana, e desvio padrão para variáveis principais (preço, quantidade vendida, etc.).
  -	Identificação de tendências ao longo do tempo (por exemplo, verificar se existem períodos com maior volume de vendas).
  -	Exploração de possíveis correlações simples, como entre preço e quantidade vendida.

2. **Critérios de Avaliação**:
  -	Capacidade de calcular e interpretar métricas estatísticas básicas.
  -	Identificação de padrões gerais ou tendências.
  -	Clareza na documentação e explicação dos insights obtidos.

**Parte 2: Visualização de Dados (40% da pontuação)**

1.	**Descrição:** Crie um dashboard simples usando Power BI ou uma ferramenta de sua escolha. O dashboard deve exibir:
  -	Visão geral das vendas por categoria de produtos.
  -	Gráfico que mostre as vendas ao longo do tempo, identificando picos ou quedas.
  -	Filtro interativo para que o usuário possa visualizar as vendas por data e categoria.
2.	**Critérios de Avaliação:**
  -	Clareza e simplicidade das visualizações.
  -	Funcionalidade e facilidade de uso do dashboard.
  -	Relevância das informações apresentadas.

**Parte 3: Interpretação e Documentação (20% da pontuação)**

1.	**Descrição:** Escreva um breve relatório ou apresentação com os principais insights e explique:
  -	Os padrões encontrados e o que podem significar para a empresa.
  -	Sugestões iniciais baseadas nos dados (por exemplo, produtos ou regiões que merecem atenção).
2.	**Critérios de Avaliação:**
  -	Capacidade de interpretar os resultados e comunicar os insights de forma clara.
  -	Qualidade da apresentação e organização dos resultados.

**Entrega e Prazos:**
O candidato deve enviar o código, as análises, e o link para o dashboard após receber o **dataset.**

**Documentação:** Cada parte deve ser acompanhada de uma breve explicação das escolhas feitas e insights obtidos.

**Recursos para o Teste:** Dataset Simulado: Criar um dataset fictício com colunas como: Data da Venda, Categoria, Produto, Preço, Quantidade Vendida, e Região.

**Ferramentas sugeridas:** Python (pandas, numpy), Power BI ou Tableau.
________________________________________

# **Informações para leitura do arquivo**
As anotações feitas são referentes aos trechos de códigos imediatamente abaixo delas, salvo os comentários feitos sobre o dashboard no final do arquivo.

É importante que não reinicie esse jupyternotebook pois os arquivos podem não estar no mesmo diretório de quando criados.

# **Parte 1:**
"""

from google.colab import drive
drive.mount('/content/drive')

"""Importação das bibliotecas usadas."""

import pandas as pd, numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""Lendo o arquivo"""

df = pd.read_csv('/content/drive/MyDrive/dataset_vendas.csv')

"""Mostrando as primeiras linhas.

Logo de cara vemos que alguns produtos estão com a categoria errada, como o Celular na categoria de Beleza.
"""

df.head()

"""Identificando os produtos e categorias existentes."""

df['produto'].unique()

df['categoria'].unique()

"""Criando um dicionário para associar cada produto à sua categoria correta."""

categorias_produtos = {
    'Celular': 'Eletrônicos',
    'Calça': 'Roupas',
    'Câmera': 'Eletrônicos',
    'Vestido': 'Roupas',
    'Laptop': 'Eletrônicos',
    'Casaco': 'Roupas',
    'Perfume': 'Beleza',
    'Maquiagem': 'Beleza',
    'Shampoo': 'Beleza',
    'Creme': 'Beleza',
    'Fone de Ouvido': 'Eletrônicos',
    'Bola de Futebol': 'Esportes',
    'Raquete': 'Esportes',
    'Capacete': 'Esportes',
    'Corda': 'Esportes',
    'Camisa': 'Roupas',
    'Biografia': 'Livros',
    'Técnico': 'Livros',
    'Ficção Científica': 'Livros',
    'Romance': 'Livros'
}

"""Função que aplica no dataframe o dicionário para corrigir os erros."""

df['categoria'] = df['produto'].map(categorias_produtos)

"""Mostrando que agora está certo."""

df.head()

"""Salvando o arquivo corrigido para usar no PowerBI."""

df.to_csv('/content/drive/MyDrive/dataset_vendas_corrigido.csv')

"""Verificando se existem valores ausentes.

Todos estão completos.
"""

df.isna().sum()

"""Verificando os tipos das variáveis.

Todas dentro do esperado.
"""

df.info()

"""Calculando estatísticas básicas das variáveis numéricas.

O alto desvio padrão no preço nos revela uma ampla faixa de valores dos produtos.

O preço mínimo de 12,54 reais aparentava ser um outlier. Entretanto, uma análise mais minuciosa revelou se tratar de um livro, o que é aceitável dentro do contexto de vendas.
"""

df.describe()

"""Agrupando por data de venda e quantidade vendida para ver em quais datas foram vendidos mais produtos.

A princípio não se pode tirar nenhuma conclusão, seria necessário investigar mais a fundo a fim de identificar se foi alguma promoção realizada ou somente um aumento sazonal de vendas.
"""

df['data_venda'] = pd.to_datetime(df['data_venda'])
df_vendas_tempo = df.groupby('data_venda')['quantidade_vendida'].sum().reset_index()
df_vendas_tempo = df_vendas_tempo.sort_values(by='quantidade_vendida', ascending=False).reset_index()
print(df_vendas_tempo)

"""Observando também a região que mais vendeu."""

df_vendas_regiao = df.groupby('regiao')['quantidade_vendida'].sum().reset_index()
df_vendas_regiao = df_vendas_regiao.sort_values(by='quantidade_vendida', ascending=False).reset_index()
print(df_vendas_regiao)

"""Aplicando o método de One Hot Encoding para converter as variáveis categóricas em binárias a fim de calcular a matriz de correlação do dataframe."""

df_corr = pd.get_dummies(df, columns=['categoria', 'produto', 'regiao'])
matriz_corr = df_corr.corr()
matriz_corr.head()

"""Aplicando um limite de 0.3 (correlação ainda fraca) para facilitar a leitura do gráfico na busca de uma relação entre as variáveis.

O resultado mostra somente uma relação entre os produtos e as suas respectivas categorias, não se revelando importante para a análise.

A relação entre preço e quantidade vendida ficou abaixo de 0.1, revelando que influenciam um ao outro muito pouco.
"""

limite = 0.3
mask = np.abs(matriz_corr) < limite

plt.figure(figsize=(12, 10))
sns.heatmap(matriz_corr, mask = mask, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Heatmap de Correlação')
plt.show()

"""# **Parte 2:**"""

from IPython.display import Image, display

"""Abaixo está uma captura de tela do Dashboard feito no Power BI.

O arquivo estará no email junto a este jupyternotebook.
"""

display(Image(filename='/content/drive/MyDrive/dashboard_integral_trust.png'))

"""# **Parte** 3:

Observando os dois gráficos de colunas, percebemos que a categoria de beleza está mais distante das outras, tanto no total de venda quanto na média.

Reforçando esse fato, no gráfico de barras nós percebemos que produtos como creme e casaco estão no final da lista, demonstrando uma menor quantidade vendida quando comparados com outros produtos.

Dito isso, é válido estudar uma possível intervenção para aumentar as vendas do setor de beleza. Também é importante monitorar a categoria de roupas, uma vez que alguns de seus produtos não estão vendendo tanto quanto os outros.

-------------------------------------------------------------------------------
Passando agora para o gráfico de linhas, percebemos três principais períodos em que as vendas foram preocupantes: Março, Agosto e Setembro.

É importante tomar medidas para incentivar os clientes a comprarem nesses períodos. Em uma análise mais detalhada é possível identificar os produtos menos vendidos nessa época e realizar alguma promoção ou campanha para ajudar nas vendas do mês. Laptops, livros de ficção científica e shampoo são alguns dos que menos venderam em Março, por exemplo.

--------------------------------------------------------------------------------
Quanto as regiões, temos que na Centro-Oeste a categoria de eletrônicos prevalece. Na Leste e Oeste predominam os livros, na Norte as roupas e no Sul os esportes.

Essa informação é essencial pois permite focar nos produtos das categorias que mais vendem nessas regiões, atendendo ao desejo dos clientes.

Vale ainda citar que a região Sul foi a que menos vendeu em termos de quantidades, sendo necessário estudar a clientela e seus interesses para melhorar os resultados.

# **Conclusão**:
O setor de beleza precisa de medidas para alavancar suas vendas, assim como é interessante estudar mais as movimentações da categoria de roupas.

Alguns meses necessitam de um olhar urgente, pois as vendas nesses períodos estão abaixo da média anual.

As vendas por categoria variam a depender da região, revelando uma possibilidade de investimento direcional nos produtos mais vendidos em cada área. Ainda, as vendas na região Sul se mostraram preocupantes e valem a atenção.
"""